import "./globals.css";
import { Toaster } from "sonner";
import ConvexClientProvider from "./ConvexClientProvider";
import Provider from "./provider";

export const metadata = {
  title: "Code Mind AI",
  description: "Generated by create next app",
  icons: {
    icon: "./vercel.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background">
        <ConvexClientProvider>
          <Provider>{children}</Provider>
          <Toaster />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
